import { Router, type IRouter, type Request, type Response } from "express";
import crypto from "node:crypto";
import { generateMemeImage } from "../lib/image-gen.js";
import { animateImage } from "../lib/runway.js";
import { getInstallationToken, postIssueComment, postDiscussionComment } from "../lib/github.js";
import { db, processedWebhooksTable, memePostsTable } from "@workspace/db";
import { logger } from "../lib/logger.js";

const router: IRouter = Router();

function verifySignature(secret: string, rawBody: Buffer, signature: string): boolean {
  const hmac = crypto.createHmac("sha256", secret);
  hmac.update(rawBody);
  const digest = `sha256=${hmac.digest("hex")}`;
  try {
    return crypto.timingSafeEqual(Buffer.from(digest, "utf8"), Buffer.from(signature, "utf8"));
  } catch {
    return false;
  }
}

function extractKeyword(body: string): string | null {
  const match = body.match(/@gitslopbot\s+(.+?)(?:\r?\n|$)/i);
  if (!match) return null;
  const keyword = match[1].trim();
  return keyword.length > 0 ? keyword : null;
}

function normalizePrivateKey(raw: string): string {
  let key = raw.replace(/\\n/g, "\n");
  if (!key.includes("\n")) {
    const header = "-----BEGIN RSA PRIVATE KEY-----";
    const footer = "-----END RSA PRIVATE KEY-----";
    const body = key.replace(header, "").replace(footer, "").trim();
    const lines = body.match(/.{1,64}/g) ?? [];
    key = `${header}\n${lines.join("\n")}\n${footer}`;
  }
  return key;
}

async function processMemeInBackground(opts: {
  keyword: string;
  owner: string;
  repo: string;
  issueNumber: number;
  isDiscussion: boolean;
  discussionNodeId?: string;
  githubUrl: string;
  privateKey: string;
  appId: string;
  installationId: number;
}): Promise<void> {
  const { keyword, owner, repo, issueNumber, isDiscussion, discussionNodeId, githubUrl, privateKey, appId, installationId } = opts;

  let videoUrl: string | null = null;
  let imagePrompt: string | null = null;

  try {
    logger.info({ keyword }, "Starting AI meme generation pipeline");
    const { imageBase64, imagePrompt: prompt } = await generateMemeImage(keyword);
    imagePrompt = prompt;
    logger.info({ keyword, imagePrompt }, "Image generated by OpenAI DALL-E");

    videoUrl = await animateImage(imageBase64, keyword);
    logger.info({ keyword, videoUrl }, "Video generated by Runway");
  } catch (err) {
    logger.error({ err, keyword }, "AI meme generation pipeline failed");
  }

  const replyBody = videoUrl
    ? `🎬 **AI Brainrot Meme Generated!**\n\n**[▶ Watch Video](${videoUrl})**\n\n> *Prompt: "${imagePrompt ?? keyword}"*`
    : `😔 Couldn't generate a brainrot meme this time. The AI gods were not in our favor.\n\n> *Attempted for: \`${keyword}\`*`;

  try {
    const installationToken = await getInstallationToken(appId, privateKey, installationId);
    if (isDiscussion && discussionNodeId) {
      await postDiscussionComment(installationToken, discussionNodeId, replyBody);
    } else {
      await postIssueComment(installationToken, owner, repo, issueNumber, replyBody);
    }
    logger.info({ owner, repo, issueNumber, keyword, hasVideo: !!videoUrl }, "Posted meme reply to GitHub");
  } catch (err) {
    logger.error({ err }, "Failed to post GitHub comment");
  }

  if (videoUrl) {
    try {
      await db.insert(memePostsTable).values({
        keyword,
        videoUrl,
        imagePrompt,
        githubUrl,
        owner,
        repo,
        issueNumber,
      });
    } catch (err) {
      logger.warn({ err }, "Failed to save meme post to DB");
    }
  }
}

router.post(
  "/webhook/github",
  async (req: Request, res: Response): Promise<void> => {
    const webhookSecret = process.env.GITHUB_WEBHOOK_SECRET;
    const appId = process.env.GITHUB_APP_ID;
    const rawPrivateKey = process.env.GITHUB_APP_PRIVATE_KEY;

    if (!webhookSecret || !appId || !rawPrivateKey) {
      req.log.error({ hasSecret: !!webhookSecret, hasAppId: !!appId, hasPrivateKey: !!rawPrivateKey }, "Missing required environment variables");
      res.status(500).json({ error: "Server configuration error" });
      return;
    }

    const privateKey = normalizePrivateKey(rawPrivateKey);

    const signature = req.headers["x-hub-signature-256"] as string | undefined;
    const rawBody = (req as Request & { rawBody?: Buffer }).rawBody;

    if (!signature || !rawBody) {
      req.log.warn("Webhook request missing signature or raw body");
      res.status(400).json({ error: "Missing signature or body" });
      return;
    }

    if (!verifySignature(webhookSecret, rawBody, signature)) {
      req.log.warn("Invalid webhook signature");
      res.status(401).json({ error: "Invalid signature" });
      return;
    }

    const deliveryId = req.headers["x-github-delivery"] as string | undefined;
    const event = req.headers["x-github-event"] as string | undefined;

    const isDiscussion = event === "discussion_comment";
    if (event !== "issue_comment" && event !== "pull_request_review_comment" && !isDiscussion) {
      res.json({ ok: true, skipped: "unhandled event" });
      return;
    }

    const payload = req.body as Record<string, unknown>;

    if (payload.action !== "created") {
      res.json({ ok: true, skipped: "not a create action" });
      return;
    }

    const sender = payload.sender as Record<string, unknown> | undefined;
    if ((sender?.type as string) === "Bot") {
      res.json({ ok: true, skipped: "bot loop prevention" });
      return;
    }

    const comment = payload.comment as Record<string, unknown> | undefined;
    const commentBody = (comment?.body as string) ?? "";
    const commentHtmlUrl = (comment?.html_url as string | undefined) ?? "";

    if (!commentBody.toLowerCase().includes("@gitslopbot")) {
      res.json({ ok: true, skipped: "no mention" });
      return;
    }

    const keyword = extractKeyword(commentBody);
    if (!keyword) {
      res.json({ ok: true, skipped: "no keyword after mention" });
      return;
    }

    if (deliveryId) {
      const inserted = await db
        .insert(processedWebhooksTable)
        .values({ deliveryId })
        .onConflictDoNothing()
        .returning({ id: processedWebhooksTable.deliveryId });
      if (inserted.length === 0) {
        req.log.info({ deliveryId }, "Duplicate delivery — skipping");
        res.json({ ok: true, skipped: "duplicate delivery" });
        return;
      }
    }

    const installation = payload.installation as Record<string, unknown> | undefined;
    const installationId = installation?.id as number | undefined;
    if (!installationId) {
      req.log.error("Missing installation ID in payload");
      res.status(400).json({ error: "Missing installation info" });
      return;
    }

    const repository = payload.repository as Record<string, unknown> | undefined;
    const owner = ((repository?.owner as Record<string, unknown> | undefined)?.login as string | undefined) ?? "";
    const repo = (repository?.name as string | undefined) ?? "";
    const issue = payload.issue as Record<string, unknown> | undefined;
    const pullRequest = payload.pull_request as Record<string, unknown> | undefined;
    const discussion = payload.discussion as Record<string, unknown> | undefined;
    const discussionNodeId = discussion?.node_id as string | undefined;
    const issueNumber =
      (issue?.number as number | undefined) ??
      (pullRequest?.number as number | undefined) ??
      (discussion?.number as number | undefined) ?? 0;

    if (!owner || !repo || !issueNumber) {
      req.log.error({ owner, repo, issueNumber }, "Missing repository info");
      res.status(400).json({ error: "Missing repository info in payload" });
      return;
    }

    req.log.info({ owner, repo, issueNumber, keyword }, "GitSlop triggered — async AI pipeline starting");

    const githubUrl = commentHtmlUrl || `https://github.com/${owner}/${repo}/issues/${issueNumber}`;

    setImmediate(() => {
      processMemeInBackground({
        keyword,
        owner,
        repo,
        issueNumber,
        isDiscussion,
        discussionNodeId,
        githubUrl,
        privateKey,
        appId,
        installationId,
      }).catch((err) => logger.error({ err }, "Unhandled error in background meme processing"));
    });

    res.json({ ok: true, keyword, processing: true });
  },
);

export default router;
